name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-nginx-app .

      - name: Run Nginx Locally (for Testing)
        run: |
          docker run -d -p 8080:80 my-nginx-app
          echo "App is running at http://localhost:8080"
