name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t simple-nginx-app-cicd .

      - name: Verify Nginx is Running
        run: |
          curl --fail http://localhost:8080 || exit 1

