name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker Image
        run: |
          REPOSITORY_URI=<your_ecr_repository_uri>  # Replace with your ECR repository URI
          IMAGE_TAG=latest

          docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  #        docker push $REPOSITORY_URI:$IMAGE_TAG

  # deploy:
  #   needs: build-and-deploy
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Install SSH Client
  #       run: sudo apt-get install -y openssh-client

  #     - name: SSH into EC2 and Deploy Docker Image
  #       run: |
  #         ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@<EC2_INSTANCE_PUBLIC_IP> << 'EOF'
  #         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <ecr_repository_uri>
  #         docker pull <ecr_repository_uri>:latest
  #         docker run -d -p 80:80 <_ecr_repository_uri>:latest
  #         EOF