name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t simple-nginx-app-cicd .

      - name: Run Nginx Locally (for Testing)
        run: |
          docker run -d -p 8080:80 simple-nginx-app-cicd
          echo "App is running at http://localhost:8080"

      - name: Verify Nginx is Running
        run: |
          sleep 10  # Add a short delay before checking
          curl --fail http://localhost:8080 || exit 1
